### ISSUE TITLE
Problem getting player name

### ISSUE THREAD

**Issue by Nick5M420** [mahanmoulaei/JLRP-RadioList#1]
im on qb core, and the script errors when i try to use "use rp name"

**Comment by mahanmoulaei** [comment]
I have never worked with qb-core myself so I don't know about its built-in functions to get players' RP names properly.
I just updated the resource. Download the latest version and let me if the issue is fixed or not.

**Comment by Nick5M420** [comment]
> 

hey thanks, i will let you know if it worked or not asap. i put it in restarted server and ofc cfx shits itself :D

**Comment by Nick5M420** [comment]
hell yea it worked great thank you! great release honestly

**Comment by mahanmoulaei** [comment]
Perfect!
Thanks 
If there are anymore issues let me know.
