### ISSUE TITLE
Radio undefined

### ISSUE THREAD

**Issue by DarinBeard** [mahanmoulaei/JLRP-RadioList#2]
I have pma-voice and rp-radio installed and working and when I start your radio list it says the list is undefined and the html throws an error because there aren't any people in the list for the UI so it can't find it when someone talks. Am I missing a config step? I don't see anything in the config file that seems like it would help this. Thanks

![undefined](https://user-images.githubusercontent.com/793744/169302880-cbb672ca-495d-4129-be06-a2bbd4f89951.PNG)
![errors](https://user-images.githubusercontent.com/793744/169302879-8939a588-02ac-4caa-8138-4069f3329324.PNG)

**Comment by mahanmoulaei** [comment]
Do you have the latest version of pma-voice installed?

**Comment by DarinBeard** [comment]
Yes, the exports from PMA voice were not working. I had to modify them to make it work. I had two different mods that were throwing the same export error for pma-voice calls.

**Comment by mahanmoulaei** [comment]
Alright.
If there is no more problem, I'm going to close this issue.
