### ISSUE TITLE
Removing player after leaving channel

### ISSUE THREAD

**Issue by Pilpest** [mahanmoulaei/JLRP-RadioList#3]
https://gyazo.com/afe0c425badc14e3457c2308f07b09c2

Error when swapping channels, person a still see person b if person b disconnects or changes channel.

Things I've tried is delete cache and use a fresh install.

**Comment by mahanmoulaei** [comment]
I cannot reproduce this error myself.

**Comment by meltynetv2** [comment]
Yeah I can concur with the OP. I have the same issue too, happens for some users and not the rest, it's very weird as I can not reproduce it, but many players in my city have this issue :D

**Comment by mahanmoulaei** [comment]
> Yeah I can concur with the OP. I have the same issue too, happens for some users and not the rest, it's very weird as I can not reproduce it, but many players in my city have this issue :D

Ok if that’s the case, I’ll come up with a better way of coding for more consistency.

I’ll update the repo soon…

**Comment by meltynetv2** [comment]
> > Yeah I can concur with the OP. I have the same issue too, happens for some users and not the rest, it's very weird as I can not reproduce it, but many players in my city have this issue :D
> 
> Ok if that’s the case, I’ll come up with a better way of coding for more consistency.
> 
> I’ll update the repo soon…

I appreciate it sir! Thank you again for the great work regardless!

**Comment by mahanmoulaei** [comment]
> I’ll update the repo soon…

I just pushed an update. since I don't have a live server with players I can't properly test the update.
I would appreciate it if you upload the latest version on your server and check it with your players...

**Comment by mahanmoulaei** [comment]
> Thank you! I will try it soon and will get back to you on results!

Hey, any update?

**Comment by meltynetv2** [comment]
> > Thank you! I will try it soon and will get back to you on results!
> 
> Hey 👋, any update?

Yeah sorry. I have been working on an update this fix will go in on, so I am not sure if it is fixed yet. But I know the other person had the issue, so maybe they can shed some light on your fix. I will let you know as soon as I can!

**Comment by mahanmoulaei** [comment]
> > > Thank you! I will try it soon and will get back to you on results!
> > 
> > 
> > Hey 👋, any update?
> 
> Yeah sorry. I have been working on an update this fix will go in on, so I am not sure if it is fixed yet. But I know the other person had the issue, so maybe they can shed some light on your fix. I will let you know as soon as I can!

Any news? I still can't reproduce this issue myself...

**Comment by meltynetv2** [comment]
> > > > Thank you! I will try it soon and will get back to you on results!
> > > 
> > > 
> > > Hey 👋, any update?
> > 
> > 
> > Yeah sorry. I have been working on an update this fix will go in on, so I am not sure if it is fixed yet. But I know the other person had the issue, so maybe they can shed some light on your fix. I will let you know as soon as I can!
> 
> Any news? I still can't reproduce this issue myself...

Yes the issue still occurs, but I feel it is not as frequent. It happens with specific users and when more then 1 person in the radio channel. It can not be reproduced by yourself. So, I'm really not sure as I can't reproduce it myself either.

**Comment by mahanmoulaei** [comment]
> Yes the issue still occurs, but I feel it is not as frequent. It happens with specific users and when more then 1 person in the radio channel. It can not be reproduced by yourself. So, I'm really not sure as I can't reproduce it myself either.

Hmm, that's weird. I can't reproduce this issue with my friends, using the latest version on my server!
I'll keep the issue open, so somebody else might be able to notice the source of the issue...

**Comment by meltynetv2** [comment]
> > Yes the issue still occurs, but I feel it is not as frequent. It happens with specific users and when more then 1 person in the radio channel. It can not be reproduced by yourself. So, I'm really not sure as I can't reproduce it myself either.
> 
> Hmm, that's weird. I can't reproduce this issue with my friends, using the latest version on my server! I'll keep the issue open, so somebody else might be able to notice the source of the issue...

I have found the issue good sir! To replicate it you will need you and another person. Have him join a radio channel and then you join, but keep pressing the join button. I believe it's a problem with our radios rather then an issue with your resource.

But what exactly is happening is they are joining the radio station multiple times before leaving it which create multiple of them in the list and when they leave it only removes one as the others are voided out.

So maybe a check to see if they are already in a list and delete them from it and add them again on radio connect?

**Comment by mahanmoulaei** [comment]
> I have found the issue good sir! To replicate it you will need you and another person. Have him join a radio channel and then you join, but keep pressing the join button. I believe it's a problem with our radios rather then an issue with your resource.
> 
> But what exactly is happening is they are joining the radio station multiple times before leaving it which create multiple of them in the list and when they leave it only removes one as the others are voided out.
>

I will look into this.
<hr></hr>

> a check to see if they are already in a list and delete them from it and add them again on radio connect

The thing is the resource already does this on server-side. However, I will look into this more in depth.
Thank you for the info!

**Comment by mahanmoulaei** [comment]
@Pilpest @meltynetv2 The ongoing bug that you have mentioned has been fixed. You can get the updated version with the requested feature [**here**](https://github.com/XProject/x-radiolist). Feel free to open an issue in the new repository if you face any problem.
