### ISSUE TITLE
Any way to show a players server ID on the radio list?

### ISSUE THREAD

**Issue by JosephWSVRP** [mahanmoulaei/JLRP-RadioList#5]
Any way to show a players server ID on the radio list? Would be super useful for moderation in case of any slurs from someone with a changed name?
(I'm not to familiar with GitHub communications so sorry if I did anything wrong)

**Comment by mahanmoulaei** [comment]
I'll make sure to include this as a config in the next update of the resource. I'm currently working on another script at the moment so give it a bit of time...

**Comment by Legacy-TacticalGamingInteractive** [comment]
Was this added. We would love to have this too because trolls are a problem

**Comment by mahanmoulaei** [comment]
> Was this added. We would love to have this too because trolls are a problem

Not yet, but I'm working on an update for it. All ongoing bugs will be fixed & more functionalities such as seeing the player server id(only if you are admin) will be added to the resource.

**Comment by mahanmoulaei** [comment]
> `GetPlayerPed()` is kind of deprecated now FiveM says to use `PlayerPedId()` instead now as its faster apparently

That is true, but I don't understand why would you mention that here. I don't use GetPlayerPed() in any part of this resource at all...

**Comment by mahanmoulaei** [comment]
> > > `GetPlayerPed()` is kind of deprecated now FiveM says to use `PlayerPedId()` instead now as its faster apparently
> > 
> > 
> > That is true, but I don't understand why would you mention that here. I don't use GetPlayerPed() in any part of this resource at all...
> 
> Oh just in case when you update if you're going to use it idk. I see a lot of people using the old way still.

Alright thank you!

**Comment by mahanmoulaei** [comment]
@JosephWSVRP @Legacy-TacticalGamingInteractive you can get the updated version with the requested feature [**here**](https://github.com/XProject/x-radiolist). If you face any issue you are welcome to open an issue in the new repository.
