### ISSUE TITLE
Radionames not savind

### ISSUE THREAD

**Issue by SubwooferNL** [mahanmoulaei/JLRP-RadioList#6]
After a player is reconnecting it doesnt save the Name of the player when they change the name with the command but i have set the Config.ResetPlayersCustomizedNameOnExit = false	but it still resets the name.

**Comment by mahanmoulaei** [comment]
Once you restart the server everything will be back to its default. ```Config.ResetPlayersCustomizedNameOnExit = false``` only works while you don't do a server restart

**Comment by mahanmoulaei** [comment]
You can get the updated version with some changes and bug fixes [**here**](https://github.com/XProject/x-radiolist). Feel free to open an issue in the new repository if you face any problems.
